name = "toxs-craft-multiplayer"
main = "server.ts"
compatibility_date = "2026-05-26"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]
